export const categories = [
  {
    category: "General Knowledge",
    subcategories: [
      "Current Affairs",
      "World Records",
      "Famous Personalities",
      "Inventions",
      "Awards & Honors",
      "Geography Facts",
      "Important Days",
      "Historical Milestones",
      "Science Discoveries",
      "Global Organizations",
      "Human Achievements",
      "Random Facts",
      "Flags & Symbols",
      "Books & Literature",
      "Quotations & Sayings",
      "Capitals & Cities",
      "Wonders of the World",
      "Cultural Heritage",
      "Time Zones",
      "Currency & Money",
      "Measurement Units",
      "Codes & abbreviations",
      "Etiquette & Customs",
      "Nobel Prize Winners",
      "Olympic Facts",
      "Guinness World Records",
      "Famous Quotes",
      "National Symbols",
      "UNESCO Heritage Sites",
      "Royal Families",
      "Presidents & Prime Ministers",
      "First Moon Landing",
      "Titanic",
      "Ancient Wonders",
      "Modern Wonders",
      "Famous Inventors",
      "Space Exploration Facts",
      "Internet History",
      "Social Media Origins",
      "Global Pandemics",
      "World Capitals Quiz",
      "Currency Symbols",
      "Country Codes",
      "International Dialing Codes"
    ]
  },
  {
    category: "Science & Nature",
    subcategories: [
      "Biology",
      "Chemistry",
      "Physics",
      "Earth Science",
      "Environmental Science",
      "Astronomy",
      "Genetics",
      "Human Anatomy",
      "Scientific Instruments",
      "Scientific Laws & Theories",
      "Evolution & Life",
      "Science in Everyday Life",
      "Microbiology",
      "Organic Chemistry",
      "Quantum Physics",
      "Meteorology",
      "Oceanography",
      "Paleontology",
      "Biochemistry",
      "Ecology",
      "Volcanology",
      "Seismology",
      "Botany",
      "Zoology",
      "DNA Structure",
      "Theory of Relativity",
      "Newton's Laws",
      "Periodic Table",
      "Black Holes",
      "The Big Bang",
      "Natural Selection",
      "Cell Theory",
      "Plate Tectonics",
      "Photosynthesis",
      "Human Body Systems",
      "Atomic Structure",
      "Chemical Bonding",
      "Electromagnetism",
      "Thermodynamics",
      "CERN & Large Hadron Collider",
      "Famous Scientists",
      "Albert Einstein",
      "Isaac Newton",
      "Charles Darwin",
      "Marie Curie",
      "Galileo Galilei",
      "Stephen Hawking",
      "Nikola Tesla",
      "Space Exploration",
      "Climate Change",
      "Renewable Energy",
      "Endangered Species",
      "Ecosystems",
      "Solar System",
      "The Moon",
      "Earth's Layers",
      "Volcanoes",
      "Earthquakes",
      "Hurricanes & Tornadoes",
      "Oceans & Marine Life",
      "Animal Kingdom",
      "Plant Kingdom"
    ]
  },
  {
    category: "Technology & Programming",
    subcategories: [
      "Computer Science",
      "Software Development",
      "Hardware",
      "Internet & Web",
      "Artificial Intelligence",
      "Cybersecurity",
      "Data Science",
      "Machine Learning",
      "Cloud Computing",
      "Blockchain",
      "Quantum Computing",
      "Programming Languages",
      "Web Development",
      "Mobile Development",
      "DevOps",
      "Database Systems",
      "Operating Systems",
      "Networking",
      "Algorithms & Data Structures",
      "Software Architecture",
      "Version Control",
      "API Development",
      "Game Development",
      "IoT & Embedded Systems",
      "Python Programming",
      "JavaScript",
      "Java",
      "C++",
      "React.js",
      "Node.js",
      "TypeScript",
      "SQL Databases",
      "MongoDB",
      "Git & GitHub",
      "Docker",
      "Kubernetes",
      "AWS",
      "Google Cloud",
      "Microsoft Azure",
      "Apple & iOS",
      "Android Development",
      "Microsoft & Windows",
      "Linux",
      "Cyber Attacks",
      "Ethical Hacking",
      "Data Structures",
      "Algorithms",
      "Frontend Development",
      "Backend Development",
      "Full Stack Development",
      "Mobile Apps",
      "Game Engines",
      "Unity",
      "Unreal Engine",
      "Web3 & Crypto",
      "NFTs",
      "Metaverse",
      "Tech Giants",
      "Silicon Valley",
      "Startup Culture",
      "Open Source"
    ]
  },
  {
    category: "History",
    subcategories: [
      "Ancient History",
      "Medieval History",
      "Modern History",
      "World Wars",
      "Civilizations",
      "Historical Figures",
      "Colonialism",
      "Revolutions",
      "Empires & Dynasties",
      "Trade Routes",
      "Inventions in History",
      "World Heritage",
      "Renaissance",
      "Industrial Revolution",
      "Cold War",
      "Ancient Egypt",
      "Greek & Roman History",
      "Asian History",
      "African History",
      "Americas History",
      "Middle Ages",
      "Enlightenment",
      "Decolonization",
      "Archaeological Discoveries",
      "Historical Documents",
      "American Civil War",
      "French Revolution",
      "World War I Battles",
      "World War II Events",
      "American Revolution",
      "Russian Revolution",
      "The Great Depression",
      "The Holocaust",
      "Ancient Greece",
      "Ancient Rome",
      "Ancient China",
      "Maya Civilization",
      "Aztec Empire",
      "Inca Empire",
      "Ottoman Empire",
      "Mongol Empire",
      "British Empire",
      "Viking Age",
      "Samurai Japan",
      "Medieval Europe",
      "Renaissance Period",
      "The Enlightenment Era",
      "Industrial Revolution Details",
      "Cold War Events",
      "The Space Race",
      "Civil Rights Movement",
      "Women's Suffrage",
      "The Great Migration",
      "Apartheid Era",
      "The Berlin Wall",
      "September 11 Attacks",
      "The Internet Age",
      "Anc Mesopotamia",
      "Persian Empire",
      "Byzantine Empire",
      "Holy Roman Empire",
      "Spanish Conquest",
      "Napoleonic Wars",
      "Gilded Age",
      "Progressive Era",
      "Roaring Twenties",
      "Vietnam War",
      "Cuban Missile Crisis"
    ]
  },
  {
    category: "Geography",
    subcategories: [
      "Countries & Capitals",
      "Physical Geography",
      "Human Geography",
      "Maps & Globes",
      "Natural Resources",
      "Climate & Weather",
      "Oceans & Seas",
      "Mountains & Rivers",
      "Geopolitics",
      "Deserts & Forests",
      "World Borders",
      "Continents & Regions",
      "Islands & Archipelagos",
      "Volcanoes",
      "Caves & Karst",
      "Population & Demographics",
      "Urban Geography",
      "Rural Geography",
      "Time & Climate Zones",
      "Latitude & Longitude",
      "Cartography",
      "Geographic Features",
      "Regional Geography",
      "Economic Geography",
      "United States Geography",
      "European Geography",
      "Asian Geography",
      "African Geography",
      "South American Geography",
      "Australia & Oceania",
      "Antarctica",
      "The Amazon Rainforest",
      "The Sahara Desert",
      "The Himalayas",
      "The Great Barrier Reef",
      "The Nile River",
      "The Mississippi River",
      "The Grand Canyon",
      "Mount Everest",
      "The Mariana Trench",
      "The Ring of Fire",
      "The Aurora Borealis",
      "Time Zones Around the World",
      "Capital Cities",
      "Largest Cities",
      "Island Nations",
      "Landlocked Countries",
      "Country Flags",
      "US States",
      "Canadian Provinces",
      "European Countries",
      "African Countries",
      "Asian Countries",
      "South American Countries"
    ]
  },
  {
    category: "Sports",
    subcategories: [
      "Football (Soccer)",
      "Basketball",
      "Cricket",
      "Tennis",
      "Olympics",
      "Extreme Sports",
      "Athletics",
      "Esports",
      "Motorsports",
      "Sports Rules & Records",
      "Famous Athletes",
      "Winter Sports",
      "Baseball",
      "American Football",
      "Rugby",
      "Hockey",
      "Golf",
      "Boxing & MMA",
      "Swimming",
      "Cycling",
      "Volleyball",
      "Table Tennis",
      "Badminton",
      "Combat Sports",
      "Water Sports",
      "Sports Venues",
      "Sports Medicine",
      "FIFA World Cup",
      "UEFA Champions League",
      "NBA",
      "NFL Super Bowl",
      "MLB World Series",
      "Wimbledon",
      "Tour de France",
      "Formula 1",
      "NASCAR",
      "ICC Cricket World Cup",
      "Rugby World Cup",
      "Lionel Messi",
      "Cristiano Ronaldo",
      "Michael Jordan",
      "LeBron James",
      "Tom Brady",
      "Serena Williams",
      "Roger Federer",
      "Usain Bolt",
      "Muhammad Ali",
      "Michael Phelps",
      "Tiger Woods",
      "FC Barcelona",
      "Real Madrid",
      "Manchester United",
      "LA Lakers",
      "Chicago Bulls",
      "New York Yankees",
      "Dallas Cowboys",
      "India National Cricket Team",
      "Australian Cricket Team",
      "Olympic Games History",
      "Summer Olympics",
      "Winter Olympics",
      "World Cup History",
      "Ballon d'Or",
      "Sports Records",
      "FIFA World Cup Winners"
    ]
  },
  {
    category: "Mathematics & Logic",
    subcategories: [
      "Algebra",
      "Geometry",
      "Calculus",
      "Statistics",
      "Logic Puzzles",
      "Number Theory",
      "Probability",
      "Trigonometry",
      "Mathematical Constants",
      "Mathematical History",
      "Brain Teasers",
      "Patterns & Sequences",
      "Linear Algebra",
      "Discrete Mathematics",
      "Differential Equations",
      "Combinatorics",
      "Game Theory",
      "Fractals & Chaos",
      "Mathematical Proofs",
      "Complex Analysis",
      "Topology",
      "Set Theory",
      "Graph Theory",
      "Optimization",
      "Fibonacci Sequence",
      "Prime Numbers",
      "Pi (π)",
      "Golden Ratio",
      "Pythagorean Theorem",
      "Euler's Number (e)",
      "Square Roots",
      "Fractions & Decimals",
      "Percentages",
      "Ratios & Proportions",
      "Famous Mathematicians",
      "Pythagoras",
      "Euclid",
      "Leonhard Euler",
      "Carl Friedrich Gauss",
      "Alan Turing",
      "John Nash",
      "Srinivasa Ramanujan",
      "Binary Numbers",
      "Hexadecimal",
      "Logic Gates",
      "Boolean Algebra",
      "Rubik's Cube",
      "Sudoku Strategies",
      "Chess Puzzles",
      "Riddles",
      "Paradoxes",
      "Mathematical paradoxes"
    ]
  },
  {
    category: "Mythology & Philosophy",
    subcategories: [
      "Greek Mythology",
      "Roman Mythology",
      "Norse Mythology",
      "Eastern Philosophy",
      "Western Philosophy",
      "Ethics",
      "Mythical Creatures",
      "Philosophers & Thinkers",
      "Spiritual Beliefs",
      "Creation Myths",
      "Moral Dilemmas",
      "Religious Philosophy",
      "Egyptian Mythology",
      "Celtic Mythology",
      "Hindu Mythology",
      "Chinese Mythology",
      "Japanese Mythology",
      "African Mythology",
      "Native American Legends",
      "Existentialism",
      "Stoicism",
      "Epic Heroes & Legends",
      "Metaphysics",
      "Epistemology",
      "Political Philosophy",
      "Folklore & Fairy Tales",
      "Zeus",
      "Poseidon",
      "Hades",
      "Athena",
      "Apollo",
      "Hera",
      "Aphrodite",
      "Ares",
      "Hermes",
      "Dionysus",
      "Odin",
      "Thor",
      "Loki",
      "Freya",
      "Ra",
      "Anubis",
      "Osiris",
      "Isis",
      "The 12 Olympians",
      "The Titans",
      "The Trojan War",
      "The Odyssey",
      "The Iliad",
      "Jason and the Argonauts",
      "Hercules (Heracles)",
      "Perseus",
      "Theseus",
      "Achilles",
      "Socrates",
      "Plato",
      "Aristotle",
      "Confucius",
      "Lao Tzu",
      "Buddha",
      "Immanuel Kant",
      "Friedrich Nietzsche",
      "Jean-Paul Sartre",
      "Dragons",
      "Unicorns",
      "Phoenix",
      "Mermaids",
      "Vampires",
      "Werewolves",
      "Bigfoot",
      "Loch Ness Monster"
    ]
  },
  {
    category: "Movies & TV",
    subcategories: [
      "Hollywood",
      "International Cinema",
      "TV Series",
      "Animation",
      "Directors & Actors",
      "Film Genres",
      "Film Awards",
      "Cinematography",
      "Streaming Platforms",
      "Screenwriting",
      "Documentaries",
      "Classic Films",
      "Bollywood",
      "Korean Drama",
      "British TV",
      "Anime TV Shows",
      "Reality TV",
      "Sitcoms",
      "Crime & Thriller",
      "Sci-Fi & Fantasy",
      "Romance & Drama",
      "Action & Adventure",
      "Horror Movies",
      "Comedy Films",
      "Indie Cinema",
      "Film Soundtracks",
      "Movie Trivia",
      "Harry Potter",
      "Star Wars",
      "Marvel Cinematic Universe",
      "DC Universe",
      "The Lord of the Rings",
      "Game of Thrones",
      "Star Trek",
      "Jurassic Park",
      "Fast & Furious",
      "Pirates of the Caribbean",
      "The Matrix",
      "Twilight Saga",
      "Transformers",
      "Disney Classics",
      "James Bond (007)",
      "Indiana Jones",
      "The Hunger Games",
      "Marvel TV Shows",
      "DC TV Shows",
      "The Walking Dead",
      "Stranger Things",
      "The Office",
      "Friends",
      "Breaking Bad",
      "The Simpsons",
      "Disney Animation",
      "Pixar Movies",
      "Studio Ghibli",
      "Anime Movies",
      "Marvel Comics Movies",
      "DC Comics Movies",
      "Dark Universe",
      "X-Men",
      "Spider-Man",
      "Batman",
      "Superman",
      "Avengers",
      "Guardians of the Galaxy",
      "Thor",
      "Iron Man",
      "Captain America",
      "Black Panther",
      "Doctor Strange",
      "Star Wars Original Trilogy",
      "Star Wars Prequels",
      "Star Wars Sequels",
      "The Mandalorian",
      "Harry Potter Books vs Movies",
      "Fantastic Beasts",
      "Wizarding World",
      "Middle-earth",
      "The Hobbit"
    ]
  },
  {
    category: "Music",
    subcategories: [
      "Classical Music",
      "Pop Music",
      "Rock Music",
      "Jazz & Blues",
      "World Music",
      "Musical Instruments",
      "Music Theory",
      "Composers & Artists",
      "Music Awards",
      "Genres & Styles",
      "Electronic Music",
      "Cultural Music Traditions",
      "Hip-Hop & Rap",
      "Country Music",
      "R&B & Soul",
      "Reggae",
      "Punk Rock",
      "Metal Music",
      "Folk Music",
      "Opera",
      "Broadway & Musicals",
      "Music Production",
      "Music History",
      "K-Pop",
      "Latin Music",
      "Dance Music",
      "Music Videos",
      "The Beatles",
      "Michael Jackson",
      "Taylor Swift",
      "Beyoncé",
      "Drake",
      "Ed Sheeran",
      "Adele",
      "Bruno Mars",
      "Ariana Grande",
      "Billie Eilish",
      "Elvis Presley",
      "Madonna",
      "Queen",
      "Led Zeppelin",
      "Pink Floyd",
      "The Rolling Stones",
      "Bob Dylan",
      "David Bowie",
      "Prince",
      "Whitney Houston",
      "Mariah Carey",
      "Stevie Wonder",
      "Elton John",
      "Freddie Mercury",
      "Kurt Cobain",
      "Jimi Hendrix",
      "Mozart",
      "Beethoven",
      "Bach",
      "Vivaldi",
      "Chopin",
      "Tchaikovsky",
      "BTS",
      "BLACKPINK",
      "Bad Bunny",
      "The Weeknd",
      "Post Malone",
      "Dua Lipa",
      "Harry Styles",
      "Olivia Rodrigo",
      "Doja Cat",
      "Grammy Awards",
      "MTV",
      "Billboard Hot 100",
      "Rock & Roll Hall of Fame",
      "Album Covers",
      "Music Festivals",
      "Coachella",
      "Glastonbury"
    ]
  },
  {
    category: "Arts & Literature",
    subcategories: [
      "Painting",
      "Sculpture",
      "Literature",
      "Art Movements",
      "Famous Artists",
      "Literary Devices",
      "Poetry",
      "Novels & Authors",
      "Modern Art",
      "Museums & Galleries",
      "Classic Literature",
      "Art Techniques",
      "Renaissance Art",
      "Impressionism",
      "Abstract Art",
      "Photography",
      "Digital Art",
      "Contemporary Literature",
      "Science Fiction",
      "Mystery & Thriller",
      "Romance Literature",
      "Non-Fiction",
      "Biographies & Memoirs",
      "Short Stories",
      "Graphic Literature",
      "Children's Literature",
      "Art History",
      "Performing Arts",
      "Mona Lisa",
      "The Starry Night",
      "The Last Supper",
      "Guernica",
      "The Scream",
      "Girl with a Pearl Earring",
      "The Persistence of Memory",
      "American Gothic",
      "The Birth of Venus",
      "Creation of Adam",
      "Leonardo da Vinci",
      "Vincent van Gogh",
      "Pablo Picasso",
      "Michelangelo",
      "Claude Monet",
      "Rembrandt",
      "Salvador Dalí",
      "Frida Kahlo",
      "Andy Warhol",
      "Johannes Vermeer",
      "William Shakespeare",
      "Charles Dickens",
      "Jane Austen",
      "Mark Twain",
      "Ernest Hemingway",
      "F. Scott Fitzgerald",
      "George Orwell",
      "J.K. Rowling",
      "Stephen King",
      "Agatha Christie",
      "J.R.R. Tolkien",
      "C.S. Lewis",
      "Virginia Woolf",
      "Gabriel García Márquez",
      "Leo Tolstoy",
      "Fyodor Dostoevsky",
      "The Louvre",
      "The Metropolitan Museum of Art",
      "The British Museum",
      "The Vatican Museums",
      "The Uffizi Gallery",
      "Rijksmuseum",
      "The Hermitage",
      "Museum of Modern Art (MoMA)",
      "The Prado",
      "The Great Gatsby",
      "To Kill a Mockingbird",
      "1984",
      "Pride and Prejudice",
      "The Catcher in the Rye",
      "Harry Potter Series",
      "The Lord of the Rings",
      "The Hobbit",
      "The Da Vinci Code",
      "The Alchemist",
      "The Hunger Games",
      "The Twilight Saga",
      "Dune",
      "The Chronicles of Narnia"
    ]
  },
  {
    category: "Food & Culture",
    subcategories: [
      "World Cuisines",
      "Cooking Techniques",
      "Food History",
      "Cultural Traditions",
      "Festivals",
      "Beverages",
      "Regional Dishes",
      "Street Food",
      "Culinary Arts",
      "Nutrition & Diets",
      "Food Science",
      "Gastronomy",
      "Italian Cuisine",
      "Asian Cuisine",
      "Mexican Cuisine",
      "Indian Cuisine",
      "French Cuisine",
      "Mediterranean Food",
      "Desserts & Baking",
      "Vegan & Vegetarian",
      "Food Presentation",
      "Spices & Herbs",
      "Wine & Spirits",
      "Coffee & Tea",
      "Comfort Food",
      "Fusion Cuisine",
      "Traditional Recipes",
      "Pizza",
      "Sushi",
      "Pasta",
      "Burgers",
      "Tacos",
      "Curry",
      "Ramen",
      "Dim Sum",
      "Tapas",
      "Barbecue (BBQ)",
      "Falafel",
      "Samosa",
      "Pad Thai",
      "Pho",
      "Croissant",
      "Baguette",
      "Cheese",
      "Chocolate",
      "Ice Cream",
      "Donuts",
      "Pancakes",
      "Waffles",
      "Cupcakes",
      "Cookies",
      "Birthday Cake",
      "Wedding Cake",
      "Thanksgiving Dinner",
      "Christmas Food",
      "Easter Food",
      "Diwali Sweets",
      "Lunar New Year Food",
      "Chinese Food",
      "Japanese Food",
      "Thai Food",
      "Korean Food",
      "Vietnamese Food",
      "Spanish Food",
      "Greek Food",
      "Middle Eastern Food",
      "Lebanese Food",
      "Turkish Food",
      "German Food",
      "British Food",
      "American Food",
      "Brazilian Food",
      "Argentinian Food",
      "Caribbean Food",
      "African Food",
      "Coffee",
      "Espresso",
      "Cappuccino",
      "Latte",
      "Tea",
      "Green Tea",
      "Matcha",
      "Bubble Tea",
      "Beer",
      "Wine",
      "Cocktails",
      "Whiskey",
      "Vodka",
      "Rum",
      "Gin",
      "Champagne",
      "Michelin Stars",
      "Celebrity Chefs",
      "Gordon Ramsay",
      "Jamie Oliver",
      "Wolfgang Puck",
      "Anthony Bourdain",
      "Julia Child",
      "Street Food Around the World",
      "Vegan Recipes",
      "Keto Diet",
      "Mediterranean Diet",
      "Gluten-Free",
      "Superfoods",
      "Organic Food"
    ]
  },
  {
    category: "Technology Trends",
    subcategories: [
      "Artificial Intelligence",
      "Internet of Things (IoT)",
      "5G & Connectivity",
      "Virtual Reality",
      "Augmented Reality",
      "Autonomous Vehicles",
      "Wearable Tech",
      "Cybersecurity",
      "Blockchain",
      "Edge Computing",
      "Space Tech",
      "Digital Twins",
      "Biometric Technology",
      "Smart Home Devices",
      "3D Printing",
      "Gene Editing",
      "Nanotechnology",
      "Renewable Energy Tech",
      "Robotics Process Automation",
      "Extended Reality (XR)",
      "Brain-Computer Interfaces",
      "Federated Learning",
      "6G Networks",
      "Green Technology",
      "Quantum Applications"
    ]
  },
  {
    category: "Space & Astronomy",
    subcategories: [
      "Solar System",
      "Stars & Galaxies",
      "Space Exploration",
      "Astronauts",
      "Space Missions",
      "Astrophysics",
      "Cosmology",
      "Black Holes",
      "Telescopes & Observations",
      "Planets & Moons",
      "Comets & Asteroids",
      "Universe Origins",
      "Nebulae",
      "Supernovae",
      "Space Stations",
      "Satellites",
      "Rocketry",
      "Space Agencies",
      "Exoplanets",
      "Dark Matter",
      "Dark Energy",
      "Gravitational Waves",
      "Space Tourism",
      "Mars Exploration",
      "Moon Missions",
      "Astronomical Phenomena"
    ]
  },
  {
    category: "Health & Medicine",
    subcategories: [
      "Human Body",
      "Diseases & Disorders",
      "Nutrition",
      "Mental Health",
      "Medical History",
      "Healthcare Systems",
      "Vaccines & Immunology",
      "First Aid",
      "Medical Technology",
      "Public Health",
      "Alternative Medicine",
      "Anatomy & Physiology",
      "Fitness & Exercise",
      "Pharmacology",
      "Surgery",
      "Medical Ethics",
      "Epidemiology",
      "Genetics & Health",
      "Pediatrics",
      "Geriatrics",
      "Dental Health",
      "Reproductive Health",
      "Sleep Health",
      "Stress Management",
      "Medical Research"
    ]
  },
  {
    category: "Business & Finance",
    subcategories: [
      "Economics",
      "Accounting",
      "Marketing",
      "Management",
      "Personal Finance",
      "Stock Market",
      "Entrepreneurship",
      "Startups",
      "Banking Systems",
      "E-commerce",
      "Corporate Strategy",
      "Business Ethics",
      "Investment Strategies",
      "Financial Planning",
      "International Business",
      "Supply Chain Management",
      "Human Resources",
      "Business Law",
      "Real Estate",
      "Insurance",
      "Taxation",
      "Leadership",
      "Project Management",
      "Business Innovation",
      "Digital Marketing",
      "Consumer Behavior"
    ]
  },
  {
    category: "Artificial Intelligence & Machine Learning",
    subcategories: [
      "Neural Networks",
      "Deep Learning",
      "Natural Language Processing",
      "Computer Vision",
      "Reinforcement Learning",
      "AI Ethics",
      "Generative AI",
      "AI Applications",
      "Data Labeling",
      "AI in Robotics",
      "Machine Learning Algorithms",
      "AI History",
      "Supervised Learning",
      "Unsupervised Learning",
      "Transformers",
      "Large Language Models",
      "AI Safety",
      "Prompt Engineering",
      "AI in Healthcare",
      "AI in Finance",
      "Computer Vision Applications",
      "Speech Recognition",
      "AI Tools & Frameworks",
      "Feature Engineering",
      "Model Training",
      "AI Bias & Fairness"
    ]
  },
  {
    category: "Environment",
    subcategories: [
      "Climate Change",
      "Conservation",
      "Pollution",
      "Renewable Energy",
      "Ecosystems",
      "Sustainability",
      "Wildlife Protection",
      "Environmental Policies",
      "Recycling & Waste",
      "Green Technology",
      "Forests & Oceans",
      "Biodiversity",
      "Carbon Footprint",
      "Water Conservation",
      "Air Quality",
      "Soil Health",
      "Marine Conservation",
      "Endangered Habitats",
      "Environmental Activism",
      "Sustainable Living",
      "Waste Management",
      "Ocean Pollution",
      "Deforestation",
      "Greenhouse Gases",
      "Eco-friendly Products"
    ]
  },
  {
    category: "Psychology & Mind",
    subcategories: [
      "Cognitive Psychology",
      "Behavioral Psychology",
      "Personality Theories",
      "Emotional Intelligence",
      "Dreams & Consciousness",
      "Psychological Disorders",
      "Memory & Perception",
      "Motivation & Learning",
      "Social Psychology",
      "Developmental Psychology",
      "Positive Psychology",
      "Neuropsychology",
      "Brain Functions",
      "Mental Wellbeing",
      "Psychological Assessment",
      "Therapy & Counseling",
      "Stress & Anxiety",
      "Behavioral Economics",
      "Group Dynamics",
      "Perception & Sensation",
      "Child Psychology",
      "Forensic Psychology",
      "Sports Psychology",
      "Learning Disabilities"
    ]
  },
  {
    category: "Future & Innovation",
    subcategories: [
      "Space Colonization",
      "Quantum Internet",
      "Transhumanism",
      "AI Governance",
      "Climate Engineering",
      "Futuristic Architecture",
      "Smart Cities",
      "Robotic Automation",
      "Neural Interfaces",
      "Metaverse Economy",
      "Longevity Science",
      "Future Energy Sources",
      "Flying Cars",
      "Synthetic Biology",
      "Mind Uploading",
      "Dyson Spheres",
      "Terraforming",
      "Virtual Societies",
      "Future Work",
      "Space Mining",
      "Advanced Robotics",
      "Biohacking",
      "Future Medicine",
      "Nanobots",
      "Fusion Power"
    ]
  },
  {
    category: "Gaming & Esports",
    subcategories: [
      "Video Games",
      "Game Development",
      "Esports",
      "Game Design",
      "Gaming History",
      "Mobile Gaming",
      "Console Gaming",
      "PC Gaming",
      "Game Mechanics",
      "Gaming Industry",
      "Retro Games",
      "Game Theory",
      "Minecraft",
      "Fortnite",
      "League of Legends (LoL)",
      "Dota 2",
      "Counter-Strike (CS:GO)",
      "Valorant",
      "Overwatch",
      "Apex Legends",
      "Call of Duty",
      "Grand Theft Auto (GTA)",
      "Red Dead Redemption",
      "The Legend of Zelda",
      "Super Mario Bros",
      "Pokémon",
      "Animal Crossing",
      "The Sims",
      "World of Warcraft (WoW)",
      "Final Fantasy",
      "Elden Ring",
      "Dark Souls",
      "Sekiro",
      "God of War",
      "The Last of Us",
      "Horizon Zero Dawn",
      "Cyberpunk 2077",
      "Witcher 3",
      "Skyrim",
      "Fallout",
      "Assassin's Creed",
      "Resident Evil",
      "Street Fighter",
      "Tekken",
      "Mortal Kombat",
      "Super Smash Bros",
      "Nintendo Switch",
      "PlayStation 5",
      "Xbox Series X/S",
      "PC Gaming",
      "Mobile Games",
      "Genshin Impact",
      "PUBG",
      "Free Fire",
      "Roblox",
      "Among Us",
      "Angry Birds",
      "Candy Crush",
      "Tetris",
      "Pac-Man",
      "Space Invaders",
      "Pong",
      "Esports Tournaments",
      "The International (Dota 2)",
      "League of Legends World Championship",
      "Evo (Fighting Games)",
      "Fortnite World Cup",
      "Speedrunning",
      "Game Developers",
      "Nintendo",
      "Sony",
      "Microsoft",
      "Blizzard Entertainment",
      "Electronic Arts (EA)",
      "Ubisoft",
      "Rockstar Games",
      "Valve Corporation",
      "Epic Games",
      "Bethesda",
      "FromSoftware",
      "Indie Games",
      "Retro Gaming",
      "Arcade Games",
      "Gaming Terminology",
      "Gaming Culture"
    ]
  },
  {
    category: "Travel & Tourism",
    subcategories: [
      "World Landmarks",
      "Travel Destinations",
      "Cultural Tourism",
      "Adventure Travel",
      "Travel Tips",
      "World Heritage Sites",
      "Cuisine & Food Travel",
      "Ecotourism",
      "Urban Exploration",
      "Beach & Island Destinations",
      "Mountain & Nature Travel",
      "Travel Photography",
      "Eiffel Tower",
      "Statue of Liberty",
      "Great Wall of China",
      "Machu Picchu",
      "Taj Mahal",
      "Colosseum",
      "Pyramids of Giza",
      "Christ the Redeemer",
      "Sydney Opera House",
      "Big Ben",
      "Louvre Museum",
      "Mount Everest",
      "Great Barrier Reef",
      "Northern Lights (Aurora)",
      "Safari Adventures",
      "Maldives",
      "Bali",
      "Santorini",
      "Paris",
      "London",
      "New York City",
      "Tokyo",
      "Dubai",
      "Rome",
      "Barcelona",
      "Amsterdam",
      "Prague",
      "Venice",
      "Bangkok",
      "Singapore",
      "Hong Kong",
      "Los Angeles",
      "Las Vegas",
      "Miami",
      "Rio de Janeiro",
      "Cancun",
      "Cape Town",
      "Marrakech",
      "Istanbul",
      "Dubrovnik",
      "Reykjavik",
      "Queenstown",
      "Vancouver",
      "Toronto",
      "Sydney",
      "Melbourne",
      "Auckland",
      "Fiji Islands",
      "Hawaii",
      "Caribbean Islands",
      "Greek Islands",
      "Balearic Islands",
      "Croatian Coast",
      "Amalfi Coast",
      "Swiss Alps",
      "Norwegian Fjords",
      "Patagonia",
      "Alaska",
      "Yellowstone National Park",
      "Yosemite National Park",
      "Grand Canyon",
      "Niagara Falls",
      "Victoria Falls",
      "Iguazu Falls",
      "Northern Lights Tours",
      "Antarctica Expeditions",
      "Galápagos Islands",
      "Seychelles",
      "Bora Bora",
      "Travel Safety Tips",
      "Budget Travel",
      "Luxury Travel",
      "Backpacking",
      "Solo Travel",
      "Family Travel",
      "Honeymoon Destinations",
      "Adventure Activities",
      "Cultural Experiences",
      "Food Tours",
      "Wine Tasting Tours",
      "Historical Sites",
      "Religious Pilgrimages",
      "Festival Tourism",
      "Ecotourism Destinations",
      "Sustainable Travel",
      "Travel Photography Tips",
      "Backpacking Through Europe",
      "Road Trips",
      "Cruise Vacations",
      "All-Inclusive Resorts",
      "Camping & Glamping",
      "Hostels",
      "Travel Hacking",
      "Frequent Flyer Programs",
      "Travel Insurance",
      "Visa Requirements",
      "Currency Exchange",
      "Language Basics for Travelers"
    ]
  },
  {
    category: "Fashion & Design",
    subcategories: [
      "Fashion History",
      "Fashion Designers",
      "Clothing & Accessories",
      "Interior Design",
      "Graphic Design",
      "Fashion Trends",
      "Sustainable Fashion",
      "Haute Couture",
      "Street Fashion",
      "Textile Design",
      "Fashion Weeks",
      "Product Design",
      "Chanel",
      "Gucci",
      "Prada",
      "Versace",
      "Louis Vuitton",
      "Dior",
      "Hermès",
      "Balenciaga",
      "Fendi",
      "Burberry",
      "Alexander McQueen",
      "Yves Saint Laurent",
      "Christian Dior",
      "Coco Chanel",
      "Giorgio Armani",
      "Ralph Lauren",
      "Calvin Klein",
      "Tom Ford",
      "Donatella Versace",
      "Marc Jacobs",
      "Stella McCartney",
      "Victoria Beckham",
      "Fashion Weeks",
      "Paris Fashion Week",
      "Milan Fashion Week",
      "New York Fashion Week",
      "London Fashion Week",
      "Vintage Fashion",
      "80s Fashion",
      "90s Fashion",
      "Minimalist Design",
      "Scandinavian Design",
      "Industrial Design",
      "Sustainable Design",
      "UX/UI Design",
      "Logo Design",
      "Typography",
      "Color Theory",
      "Brand Identity",
      "Fashion Photography",
      "Fashion Magazines",
      "Vogue",
      "Elle",
      "Harper's Bazaar",
      "Fashion Influencers",
      "Fashion Blogs",
      "Fashion Icons",
      "Audrey Hepburn",
      "Marilyn Monroe",
      "Princess Diana",
      "Kate Moss",
      "Naomi Campbell",
      "Gisele Bündchen",
      "Fashion Capitals",
      "Silk",
      "Cotton",
      "Wool",
      "Denim",
      "Leather",
      "Lace",
      "Velvet",
      "Sustainable Materials",
      "Fashion Technology",
      "3D Printed Fashion",
      "Smart Clothing"
    ]
  },
  {
    category: "Politics & Law",
    subcategories: [
      "Government Systems",
      "International Relations",
      "Political Ideologies",
      "Constitutional Law",
      "Human Rights",
      "Diplomacy",
      "Political History",
      "Legal Systems",
      "Civil Rights",
      "Political Leaders",
      "Public Policy",
      "International Law",
      "Democracy",
      "Monarchy",
      "Communism",
      "Socialism",
      "Capitalism",
      "Fascism",
      "Anarchism",
      "Liberalism",
      "Conservatism",
      "The United Nations",
      "NATO",
      "European Union",
      "The White House",
      "The Pentagon",
      "Buckingham Palace",
      "The Kremlin",
      "The US Constitution",
      "The Bill of Rights",
      "Magna Carta",
      "The Geneva Conventions",
      "Human Rights Act",
      "Supreme Court",
      "International Court of Justice",
      "Criminal Law",
      "Civil Law",
      "Corporate Law",
      "Family Law",
      "Intellectual Property Law",
      "Environmental Law",
      "Tax Law",
      "Voting Systems",
      "Electoral College",
      "Parliament",
      "Congress",
      "Senate",
      "House of Representatives",
      "Prime Minister",
      "President",
      "Dictatorship",
      "Revolution",
      "Cold War Politics",
      "Nuclear Weapons",
      "Treaties",
      "Alliances",
      "Trade Wars",
      "Sanctions",
      "Embassies",
      "Diplomatic Immunity",
      "Political Parties",
      "Elections",
      "Campaigns",
      "Lobbying",
      "Political Corruption",
      "Political Scandals",
      "Impeachment",
      "Cabinet",
      "Bureaucracy",
      "Federalism",
      "Sovereignty",
      "Globalization",
      "Nationalism",
      "Populism",
      "Terrorism",
      "Security Council",
      "Peacekeeping",
      "International Aid",
      "Refugees & Asylum"
    ]
  },
  {
    category: "Languages & Linguistics",
    subcategories: [
      "World Languages",
      "Grammar & Syntax",
      "Language Families",
      "Etymology",
      "Linguistics Theory",
      "Translation",
      "Dialects & Accents",
      "Writing Systems",
      "Language Learning",
      "Historical Linguistics",
      "Sociolinguistics",
      "Semantics",
      "English Language",
      "Spanish Language",
      "Mandarin Chinese",
      "Hindi",
      "Arabic",
      "French",
      "German",
      "Japanese",
      "Russian",
      "Portuguese",
      "Italian",
      "Korean",
      "Latin",
      "Greek",
      "Sanskrit",
      "Hebrew",
      " sign Language",
      "Esperanto",
      "English Grammar",
      "Spanish Grammar",
      "French Grammar",
      "German Grammar",
      "Verb Tenses",
      "Nouns & Pronouns",
      "Adjectives & Adverbs",
      "Prepositions",
      "Sentence Structure",
      "Punctuation",
      "Spelling",
      "Vocabulary",
      "Idioms & Phrases",
      "Proverbs",
      "Slang",
      "Formal vs Informal Language",
      "Language Origins",
      "Word History",
      "Borrowed Words",
      "False Friends",
      "Homonyms",
      "Synonyms & Antonyms",
      "Palindromes",
      "Anagrams",
      "Acronyms & Abbreviations",
      "Alphabet",
      "Phonetics",
      "Phonology",
      "Morphology",
      "Syntax",
      "Pragmatics",
      "Discourse Analysis",
      "Language Acquisition",
      "Second Language Learning",
      "Bilingualism",
      "Multilingualism",
      "Dialectology",
      "Sociolinguistics",
      "Psycholinguistics",
      "Computational Linguistics",
      "Historical Linguistics",
      "Comparative Linguistics",
      "Indo-European Languages",
      "Sino-Tibetan Languages",
      "Afro-Asiatic Languages",
      "Austronesian Languages",
      "Language Extinction",
      "Endangered Languages",
      "Language Revival",
      "Constructed Languages",
      "Code-Switching",
      "Translation Theory",
      "Machine Translation"
    ]
  },
  {
    category: "Architecture",
    subcategories: [
      "Architectural Styles",
      "Famous Architects",
      "Building Types",
      "Urban Design",
      "Landscape Architecture",
      "Sustainable Architecture",
      "Ancient Architecture",
      "Modern Architecture",
      "Interior Architecture",
      "Structural Engineering",
      "Architectural History",
      "Green Building",
      "Gothic Architecture",
      "Romanesque Architecture",
      "Baroque Architecture",
      "Renaissance Architecture",
      "Neoclassical Architecture",
      "Art Deco",
      "Brutalism",
      "Bauhaus",
      "Modernism",
      "Postmodernism",
      "Contemporary Architecture",
      "Vernacular Architecture",
      "Islamic Architecture",
      "Byzantine Architecture",
      "Greek Architecture",
      "Roman Architecture",
      "Egyptian Architecture",
      "Asian Architecture",
      "Japanese Architecture",
      "Chinese Architecture",
      "Indian Architecture",
      "Frank Lloyd Wright",
      "Zaha Hadid",
      "Le Corbusier",
      "Mies van der Rohe",
      "Antoni Gaudí",
      "I.M. Pei",
      "Frank Gehry",
      "Norman Foster",
      "Renzo Piano",
      "Santiago Calatrava",
      "Skyscrapers",
      "The Eiffel Tower",
      "The Empire State Building",
      "Burj Khalifa",
      "The Gherkin",
      "The Shard",
      "Sydney Opera House",
      "Fallingwater",
      "The Guggenheim Museum",
      "The Taj Mahal",
      "The Colosseum",
      "The Parthenon",
      "The Pyramids",
      "The Great Wall of China",
      "Notre-Dame Cathedral",
      "St. Peter's Basilica",
      "Hagia Sophia",
      "Blue Mosque",
      "Taj Mahal",
      "Petra",
      "Machu Picchu",
      "Angkor Wat",
      "Residential Architecture",
      "Commercial Architecture",
      "Industrial Architecture",
      "Religious Architecture",
      "Public Spaces",
      "Urban Planning",
      "City Design",
      "Landscape Design",
      "Parks & Gardens",
      "Sustainable Design",
      "Passive Solar Design",
      "Green Roofs",
      "Smart Buildings",
      "Adaptive Reuse",
      "Historic Preservation",
      "Building Materials",
      "Concrete",
      "Steel",
      "Glass",
      "Wood",
      "Stone",
      "Brick",
      "Architectural Drawings",
      "Blueprints",
      "3D Modeling",
      "CAD Software",
      "Interior Design Styles",
      "Minimalist Architecture",
      "Scandinavian Architecture",
      "Mediterranean Architecture",
      "Tropical Architecture",
      "Desert Architecture"
    ]
  },
  {
    category: "Transportation",
    subcategories: [
      "Automotive",
      "Aviation",
      "Railways",
      "Public Transit",
      "Maritime",
      "Transport Infrastructure",
      "Electric Vehicles",
      "Transport History",
      "Traffic Systems",
      "Logistics & Supply Chain",
      "Future Transportation",
      "Vehicle Safety"
    ]
  },
  {
    category: "Animals & Wildlife",
    subcategories: [
      "Mammals",
      "Birds",
      "Reptiles & Amphibians",
      "Marine Life",
      "Insects & Arachnids",
      "Endangered Species",
      "Animal Behavior",
      "Wildlife Conservation",
      "Pets & Domestic Animals",
      "Animal Habitats",
      "Zoology",
      "Extinct Animals",
      "Lions",
      "Tigers",
      "Elephants",
      "Giraffes",
      "Zebras",
      "Hippos",
      "Rhinos",
      "Cheetahs",
      "Leopards",
      "Jaguars",
      "Wolves",
      "Foxes",
      "Bears",
      "Polar Bears",
      "Panda Bears",
      "Kodiak Bears",
      "Grizzly Bears",
      "Deer",
      "Moose",
      "Elk",
      "Bison",
      "Kangaroos",
      "Koalas",
      "Wallabies",
      "Monkeys",
      "Gorillas",
      "Chimpanzees",
      "Orangutans",
      "Baboons",
      "Dolphins",
      "Whales",
      "Sharks",
      "Sea Turtles",
      "Octopus",
      "Squid",
      "Jellyfish",
      "Coral Reefs",
      "Penguins",
      "Seals",
      "Sea Lions",
      "Walruses",
      "Eagles",
      "Hawks",
      "Owls",
      "Falcons",
      "Parrots",
      "Flamingos",
      "Penguins",
      "Peacocks",
      "Swans",
      "Dogs",
      "Cats",
      "Horses",
      "Rabbits",
      "Hamsters",
      "Guinea Pigs",
      "Fish Pets",
      "Reptile Pets",
      "Bird Pets",
      "Dog Breeds",
      "Cat Breeds",
      "Snakes",
      "Lizards",
      "Turtles",
      "Crocodiles",
      "Alligators",
      "Frogs",
      "Toads",
      "Spiders",
      "Scorpions",
      "Butterflies",
      "Bees",
      "Ants",
      "Dragonflies",
      "Ladybugs",
      "Dinosaurs",
      "T-Rex",
      "Velociraptor",
      "Triceratops",
      "Stegosaurus",
      "Brachiosaurus",
      "Pterodactyl",
      "Woolly Mammoth",
      "Sabertooth Tiger",
      "Dodo Bird",
      "Passenger Pigeon",
      "Tasmanian Tiger",
      "Siberian Tiger",
      "Snow Leopard",
      "Mountain Gorilla",
      "Blue Whale",
      "Giant Panda",
      "Sea Otter",
      "Red Panda",
      "Komodo Dragon",
      "Poison Dart Frog",
      "Great White Shark",
      "Hammerhead Shark",
      "Killer Whale (Orca)",
      "Animal Kingdom",
      "African Safari",
      "Amazon Rainforest Animals",
      "Australian Animals",
      "Arctic Animals",
      "Deep Sea Creatures",
      "Invasive Species",
      "Wildlife Sanctuaries",
      "National Parks",
      "Zoos",
      "Aquariums",
      "Animal Rescue",
      "Veterinary Science",
      "Animal Intelligence",
      "Animal Communication"
    ]
  },
  {
    category: "Plants & Botany",
    subcategories: [
      "Plant Biology",
      "Trees & Forests",
      "Flowers",
      "Cacti & Succulents",
      "Medicinal Plants",
      "Agriculture",
      "Gardening",
      "Plant Ecology",
      "Fungi & Mushrooms",
      "Plant Adaptations",
      "Photosynthesis",
      "Plant Classification"
    ]
  },
  {
    category: "Comics & Anime",
    subcategories: [
      "Comic Books",
      "Manga",
      "Anime",
      "Superheroes",
      "Graphic Novels",
      "Comic Strips",
      "Animation Studios",
      "Cosplay",
      "Comic History",
      "Webcomics",
      "Character Design",
      "Storytelling in Comics",
      "One Piece",
      "Naruto",
      "Dragon Ball Z",
      "Attack on Titan",
      "Demon Slayer",
      "Jujutsu Kaisen",
      "My Hero Academia",
      "Tokyo Ghoul",
      "Death Note",
      "Fullmetal Alchemist",
      "Sailor Moon",
      "Pokemon Anime",
      "Yu-Gi-Oh!",
      "Bleach",
      "One Punch Man",
      "Mob Psycho 100",
      "Hunter x Hunter",
      "One Punch Man",
      "Spy x Family",
      "Chainsaw Man",
      "Blue Lock",
      "Cyberpunk: Edgerunners",
      "Studio Ghibli",
      "Spirited Away",
      "My Neighbor Totoro",
      "Princess Mononoke",
      "Howl's Moving Castle",
      "Akira",
      "Ghost in the Shell",
      "Cowboy Bebop",
      "Neon Genesis Evangelion",
      "Dragon Ball",
      "Detective Conan",
      "Doraemon",
      "Astro Boy",
      "Marvel Comics",
      "DC Comics",
      "Batman",
      "Superman",
      "Wonder Woman",
      "Spider-Man",
      "Iron Man",
      "Captain America",
      "Thor",
      "Hulk",
      "Black Widow",
      "Deadpool",
      "Wolverine",
      "The Flash",
      "Aquaman",
      "Green Lantern",
      "The Avengers",
      "X-Men",
      "Justice League",
      "Teen Titans",
      "Watchmen",
      "The Walking Dead",
      "Scott Pilgrim",
      "Sin City",
      "Maus",
      "Persepolis",
      "Calvin & Hobbes",
      "Peanuts",
      "Garfield",
      "Dilbert",
      "XKCD",
      "Sunday Funnies",
      "Comic Con",
      "San Diego Comic-Con",
      "Cosplay Culture",
      "Fan Art",
      "Doujinshi",
      "Manhwa",
      "Manhua",
      "Webtoon",
      "Anime Conventions",
      "Otaku Culture"
    ]
  },
  {
    category: "Religion & Spirituality",
    subcategories: [
      "World Religions",
      "Religious Texts",
      "Spiritual Practices",
      "Religious History",
      "Faith & Belief",
      "Meditation & Mindfulness",
      "Religious Festivals",
      "Sacred Places",
      "Religious Leaders",
      "Comparative Religion",
      "Spiritual Traditions",
      "Religious Symbols",
      "Christianity",
      "Islam",
      "Judaism",
      "Hinduism",
      "Buddhism",
      "Sikhism",
      "Jainism",
      "Taoism",
      "Confucianism",
      "Shinto",
      "Zoroastrianism",
      "Bahá'í Faith",
      "The Bible",
      "The Quran",
      "The Torah",
      "The Vedas",
      "The Tripitaka",
      "The Guru Granth Sahib",
      "The Bhagavad Gita",
      "Prayer",
      "Worship",
      "Pilgrimage",
      "Fasting",
      "Religious Holidays",
      "Sacred Music",
      "Religious Art",
      "Church Architecture",
      "Temple Architecture",
      "Mosque Architecture",
      "Monasticism",
      "Saints & Prophets",
      "Jesus Christ",
      "Muhammad",
      "Buddha",
      "Moses",
      "Abraham",
      "Hindu Gods & Goddesses",
      "Catholicism",
      "Protestantism",
      "Orthodox Christianity",
      "Sunni Islam",
      "Shia Islam",
      "Mahayana Buddhism",
      "Theravada Buddhism",
      "Vajrayana Buddhism",
      "Hindu Denominations",
      "Jewish Denominations",
      "Mysticism",
      "Spirituality",
      "Yoga",
      "Zen",
      "Sufism",
      "Kabbalah",
      "Religious Rituals",
      "Sacraments",
      "Rites of Passage",
      "Afterlife Beliefs",
      "Creation Stories",
      "Ethics & Morality",
      " Religious Philosophy"
    ]
  },
  {
    category: "Crafts & Hobbies",
    subcategories: [
      "DIY & Crafts",
      "Knitting & Crochet",
      "Woodworking",
      "Photography",
      "Origami",
      "Pottery & Ceramics",
      "Painting & Drawing",
      "Model Building",
      "Scrapbooking",
      "Jewelry Making",
      "Calligraphy",
      "Collecting",
      "Embroidery & Cross Stitch",
      "Sewing & Quilting",
      "Weaving",
      "Spinning",
      "Paper Crafts",
      "Card Making",
      "Bookbinding",
      "Leather Crafting",
      "Metal Working",
      "Glass Blowing",
      "Mosaics",
      "Tie-Dye",
      "Batik",
      "Printmaking",
      "Sculpting",
      "Carving",
      "Candle Making",
      "Soap Making",
      "Perfume Making",
      "Home Brewing",
      "Baking",
      "Cooking",
      "Gardening",
      "Indoor Plants",
      "Bonsai",
      "Flower Arranging",
      "Landscape Design",
      "Bird Watching",
      "Astronomy",
      "Stamp Collecting",
      "Coin Collecting",
      "Antique Collecting",
      "Vinyl Records",
      "Comic Book Collecting",
      "Toy Collecting",
      "Board Games",
      "Card Games",
      "Chess",
      "Puzzles",
      "Magic Tricks",
      "Musical Instruments",
      "Singing",
      "Songwriting",
      "Creative Writing",
      "Journaling",
      "Bullet Journaling",
      "Adult Coloring",
      "DIY Home Decor",
      "Upcycling",
      "Furniture Restoration",
      "Clock Making",
      "Watch Repair",
      "Electronics DIY",
      "3D Printing",
      "Laser Cutting",
      "CNC Machining",
      "Robotics as a Hobby",
      "Drone Flying",
      "RC Vehicles",
      "Amateur Radio",
      "Geocaching",
      "Metal Detecting",
      "Caving",
      "Hiking",
      "Camping",
      "Fishing",
      "Hunting",
      "Archery",
      "Fencing",
      "Martial Arts"
    ]
  },
  {
    category: "Communication & Media",
    subcategories: [
      "Journalism",
      "Social Media",
      "Advertising",
      "Public Relations",
      "Mass Media",
      "Digital Marketing",
      "Broadcasting",
      "Content Creation",
      "Media Ethics",
      "News & Current Events",
      "Media Theory",
      "Brand Communication",
      "Famous Journalists",
      "News Networks",
      "Investigative Journalism",
      "Photojournalism",
      "Editorial Writing",
      "Citizen Journalism",
      "Fake News & Media Literacy",
      "Pulitzer Prize",
      "War Correspondents",
      "Broadcast Journalism",
      "History of Television",
      "History of Radio",
      "Print Media History",
      "Digital Revolution",
      "Media Moguls",
      "Newspaper Barons",
      "Marketing Campaigns",
      "Brand Mascots",
      "Super Bowl Commercials",
      "Print Advertising",
      "TV Commercials",
      "Advertising Slogans",
      "Logo Evolution",
      "Marketing Strategies",
      "Influencer Marketing",
      "Social Media History",
      "Viral Content",
      "Hashtags & Trends",
      "Social Media Metrics",
      "Digital Communities",
      "TV Networks",
      "Radio Networks",
      "Cable Television",
      "Satellite Radio",
      "Podcasts",
      "Propaganda",
      "Censorship",
      "Freedom of Speech",
      "Communication Models",
      "Non-verbal Communication",
      "Public Speaking",
      "Rhetoric",
      "Debate",
      "Internet Culture",
      "Memes",
      "Online Communities",
      "Digital Privacy",
      "Net Neutrality",
      "Social Media Algorithms"
    ]
  },
  {
    category: "Education",
    subcategories: [
      "Teaching Methods",
      "Educational Technology",
      "Learning Theories",
      "Education Systems",
      "Higher Education",
      "Early Childhood Education",
      "Online Learning",
      "Educational Psychology",
      "Curriculum Design",
      "Special Education",
      "Educational History",
      "Student Development",
      "Famous Educators",
      "Educational Philosophers",
      "Pedagogy",
      "Assessment & Testing",
      "Educational Reform",
      "Education Policy",
      "School Systems",
      "Homeschooling",
      "Montessori Education",
      "Waldorf Education",
      "Reggio Emilia Approach",
      "International Baccalaureate",
      "Vocational Education",
      "Adult Education",
      "Continuing Education",
      "Distance Learning",
      "MOOCs",
      "E-Learning Platforms",
      "Educational Apps",
      "Gamification in Education",
      "Project-Based Learning",
      "Experiential Learning",
      "Blended Learning",
      "Flipped Classroom",
      "STEM Education",
      "STEAM Education",
      "Liberal Arts",
      "Classical Education",
      "Critical Thinking",
      "Problem Solving",
      "Study Skills",
      "Note-Taking Methods",
      "Memory Techniques",
      "Time Management",
      "Research Methods",
      "Academic Writing",
      "Presentation Skills",
      "Group Work",
      "Collaborative Learning",
      "Peer Learning",
      "Mentoring",
      "Coaching",
      "Educational Assessment",
      "Standardized Testing",
      "Intelligence Quotient (IQ)",
      "Multiple Intelligences",
      "Learning Disabilities",
      "Gifted Education",
      "Special Needs",
      "Inclusive Education",
      "Behavior Management",
      "Classroom Management",
      "School Leadership",
      "Educational Administration",
      "Education Funding",
      "Education Around the World",
      "Ancient Education Systems",
      "Medieval Education",
      "Renaissance Education",
      "Modern Education",
      "Education Technology Trends",
      "Artificial Intelligence in Education",
      "Virtual Reality in Education",
      "Digital Literacy",
      "Information Literacy",
      "Media Literacy"
    ]
  },
  {
    category: "Energy & Resources",
    subcategories: [
      "Fossil Fuels",
      "Renewable Energy",
      "Nuclear Energy",
      "Solar Power",
      "Wind Energy",
      "Hydropower",
      "Energy Storage",
      "Sustainable Resources",
      "Energy Policy",
      "Energy Efficiency",
      "Bioenergy",
      "Grid Systems",
      "Coal",
      "Petroleum & Oil",
      "Natural Gas",
      "Geothermal Energy",
      "Tidal Energy",
      "Wave Energy",
      "Biomass",
      "Hydrogen Fuel",
      "Nuclear Fission",
      "Nuclear Fusion",
      "Uranium",
      "Battery Technology",
      "Lithium-Ion Batteries",
      "Solid State Batteries",
      "Smart Grids",
      "Microgrids",
      "Energy Distribution",
      "Power Plants",
      "Electricity Generation",
      "Energy Conservation",
      "Green Building",
      "Sustainable Architecture",
      "Water Resources",
      "Freshwater",
      "Water Conservation",
      "Desalination",
      "Water Treatment",
      "Mineral Resources",
      "Mining",
      "Rare Earth Elements",
      "Copper",
      "Gold & Silver",
      "Iron Ore",
      "Aluminum",
      "Recycling",
      "Circular Economy",
      "Waste-to-Energy",
      "Carbon Footprint",
      "Carbon Capture",
      "Climate Solutions",
      "Energy Transition",
      "Clean Energy",
      "Fossil Fuel Phase-out",
      "Renewable Integration",
      "Energy Access",
      "Rural Electrification",
      "Energy Security",
      "OPEC",
      "Energy Markets",
      "Oil Prices",
      "Energy Trading",
      "Peak Oil",
      "Resource Depletion",
      "Sustainable Development",
      "Green Technology",
      "Environmental Impact"
    ]
  },
  {
    category: "Dance & Performance",
    subcategories: [
      "Dance Styles",
      "Famous Dancers",
      "Dance History",
      "Choreography",
      "Theater",
      "Performance Art",
      "Street Dance",
      "Classical Dance",
      "Folk Dance",
      "Dance Notation",
      "Stage Performance",
      "Dance & Culture"
    ]
  },
  {
    category: "Robotics",
    subcategories: [
      "Industrial Robots",
      "Service Robots",
      "Robotics Engineering",
      "Robot Sensors",
      "Autonomous Systems",
      "Robot Programming",
      "Human-Robot Interaction",
      "Robotics History",
      "Drone Technology",
      "Robotic Arms",
      "Mobile Robots",
      "Robotics Applications"
    ]
  },
  {
    category: "Materials Science",
    subcategories: [
      "Metals & Alloys",
      "Polymers",
      "Ceramics",
      "Composites",
      "Nanomaterials",
      "Smart Materials",
      "Material Properties",
      "Biomaterials",
      "Material Testing",
      "Crystallography",
      "Material Processing",
      "Sustainable Materials"
    ]
  },
  {
    category: "Cryptography & Security",
    subcategories: [
      "Encryption",
      "Cybersecurity",
      "Network Security",
      "Cryptographic Algorithms",
      "Digital Privacy",
      "Security Protocols",
      "Ethical Hacking",
      "Password Security",
      "Blockchain Security",
      "Quantum Cryptography",
      "Information Security",
      "Security Standards"
    ]
  }
];
