/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OgDotpngRouteImport } from './routes/og[.]png'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CategoryIndexRouteImport } from './routes/category.index'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as QuizSlugRouteImport } from './routes/quiz.$slug'
import { Route as RpcSplatRouteImport } from './routes/rpc.$'
import { Route as ThisDayInHistoryIndexRouteImport } from './routes/this-day-in-history.index'
import { Route as ThisDayInHistorySlugRouteImport } from './routes/this-day-in-history.$slug'
import { Route as QuizSlugOgDotpngRouteImport } from './routes/quiz.$slug.og[.]png'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDotpngRoute = OgDotpngRouteImport.update({
  id: '/og.png',
  path: '/og.png',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSlugRoute = QuizSlugRouteImport.update({
  id: '/quiz/$slug',
  path: '/quiz/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ThisDayInHistoryIndexRoute = ThisDayInHistoryIndexRouteImport.update({
  id: '/this-day-in-history/',
  path: '/this-day-in-history/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThisDayInHistorySlugRoute = ThisDayInHistorySlugRouteImport.update({
  id: '/this-day-in-history/$slug',
  path: '/this-day-in-history/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSlugOgDotpngRoute = QuizSlugOgDotpngRouteImport.update({
  id: '/og.png',
  path: '/og.png',
  getParentRoute: () => QuizSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/og.png': typeof OgDotpngRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$slug': typeof CategorySlugRoute
  '/quiz/$slug': typeof QuizSlugRouteWithChildren
  '/rpc/$': typeof RpcSplatRoute
  '/this-day-in-history/$slug': typeof ThisDayInHistorySlugRoute
  '/category/': typeof CategoryIndexRoute
  '/this-day-in-history/': typeof ThisDayInHistoryIndexRoute
  '/quiz/$slug/og.png': typeof QuizSlugOgDotpngRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/og.png': typeof OgDotpngRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$slug': typeof CategorySlugRoute
  '/quiz/$slug': typeof QuizSlugRouteWithChildren
  '/rpc/$': typeof RpcSplatRoute
  '/this-day-in-history/$slug': typeof ThisDayInHistorySlugRoute
  '/category': typeof CategoryIndexRoute
  '/this-day-in-history': typeof ThisDayInHistoryIndexRoute
  '/quiz/$slug/og.png': typeof QuizSlugOgDotpngRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/og.png': typeof OgDotpngRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$slug': typeof CategorySlugRoute
  '/quiz/$slug': typeof QuizSlugRouteWithChildren
  '/rpc/$': typeof RpcSplatRoute
  '/this-day-in-history/$slug': typeof ThisDayInHistorySlugRoute
  '/category/': typeof CategoryIndexRoute
  '/this-day-in-history/': typeof ThisDayInHistoryIndexRoute
  '/quiz/$slug/og.png': typeof QuizSlugOgDotpngRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/og.png'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/category/$slug'
    | '/quiz/$slug'
    | '/rpc/$'
    | '/this-day-in-history/$slug'
    | '/category/'
    | '/this-day-in-history/'
    | '/quiz/$slug/og.png'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/og.png'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/category/$slug'
    | '/quiz/$slug'
    | '/rpc/$'
    | '/this-day-in-history/$slug'
    | '/category'
    | '/this-day-in-history'
    | '/quiz/$slug/og.png'
  id:
    | '__root__'
    | '/'
    | '/og.png'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/category/$slug'
    | '/quiz/$slug'
    | '/rpc/$'
    | '/this-day-in-history/$slug'
    | '/category/'
    | '/this-day-in-history/'
    | '/quiz/$slug/og.png'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OgDotpngRoute: typeof OgDotpngRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CategorySlugRoute: typeof CategorySlugRoute
  QuizSlugRoute: typeof QuizSlugRouteWithChildren
  RpcSplatRoute: typeof RpcSplatRoute
  ThisDayInHistorySlugRoute: typeof ThisDayInHistorySlugRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
  ThisDayInHistoryIndexRoute: typeof ThisDayInHistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og.png': {
      id: '/og.png'
      path: '/og.png'
      fullPath: '/og.png'
      preLoaderRoute: typeof OgDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/': {
      id: '/category/'
      path: '/category'
      fullPath: '/category/'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$slug': {
      id: '/quiz/$slug'
      path: '/quiz/$slug'
      fullPath: '/quiz/$slug'
      preLoaderRoute: typeof QuizSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/this-day-in-history/': {
      id: '/this-day-in-history/'
      path: '/this-day-in-history'
      fullPath: '/this-day-in-history/'
      preLoaderRoute: typeof ThisDayInHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/this-day-in-history/$slug': {
      id: '/this-day-in-history/$slug'
      path: '/this-day-in-history/$slug'
      fullPath: '/this-day-in-history/$slug'
      preLoaderRoute: typeof ThisDayInHistorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$slug/og.png': {
      id: '/quiz/$slug/og.png'
      path: '/og.png'
      fullPath: '/quiz/$slug/og.png'
      preLoaderRoute: typeof QuizSlugOgDotpngRouteImport
      parentRoute: typeof QuizSlugRoute
    }
  }
}

interface QuizSlugRouteChildren {
  QuizSlugOgDotpngRoute: typeof QuizSlugOgDotpngRoute
}

const QuizSlugRouteChildren: QuizSlugRouteChildren = {
  QuizSlugOgDotpngRoute: QuizSlugOgDotpngRoute,
}

const QuizSlugRouteWithChildren = QuizSlugRoute._addFileChildren(
  QuizSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OgDotpngRoute: OgDotpngRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CategorySlugRoute: CategorySlugRoute,
  QuizSlugRoute: QuizSlugRouteWithChildren,
  RpcSplatRoute: RpcSplatRoute,
  ThisDayInHistorySlugRoute: ThisDayInHistorySlugRoute,
  CategoryIndexRoute: CategoryIndexRoute,
  ThisDayInHistoryIndexRoute: ThisDayInHistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
