// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'08919b85a5150acb763e400d6c86863c5ad8e48651feac6697047a7677562140'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Category: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Horoscope: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly zodiacSign:
        | 'ARIES'
        | 'TAURUS'
        | 'GEMINI'
        | 'CANCER'
        | 'LEO'
        | 'VIRGO'
        | 'LIBRA'
        | 'SCORPIO'
        | 'SAGITTARIUS'
        | 'CAPRICORN'
        | 'AQUARIUS'
        | 'PISCES';
      readonly date: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly luckyColor: CodecTypes['pg/text@1']['output'] | null;
      readonly luckyNumber: CodecTypes['pg/int4@1']['output'] | null;
      readonly mood: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly PastEvent: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly month: CodecTypes['pg/int4@1']['output'];
      readonly day: CodecTypes['pg/int4@1']['output'];
      readonly year: CodecTypes['pg/int4@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly category:
        | 'war'
        | 'discovery'
        | 'politics'
        | 'science'
        | 'art'
        | 'sports'
        | 'technology'
        | 'medicine'
        | 'exploration'
        | 'literature'
        | 'music'
        | 'economy'
        | 'religion'
        | 'disaster'
        | 'revolution'
        | 'invention';
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['output']> | null;
      readonly sourceUrls: ReadonlyArray<CodecTypes['pg/text@1']['output']> | null;
      readonly metadata: CodecTypes['pg/jsonb@1']['output'] | null;
      readonly isPublished: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly eventDate: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
    };
    readonly Question: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly quizId: CodecTypes['pg/text@1']['output'];
      readonly text: CodecTypes['pg/text@1']['output'];
      readonly options: ReadonlyArray<CodecTypes['pg/text@1']['output']> | null;
      readonly correctIndex: CodecTypes['pg/int4@1']['output'];
      readonly explanation: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Quiz: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly quizPageTitle: CodecTypes['pg/text@1']['output'];
      readonly quizPageDescription: CodecTypes['pg/text@1']['output'];
      readonly difficulty: 'easy' | 'medium' | 'hard';
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly isPublished: CodecTypes['pg/bool@1']['output'];
      readonly publishedAt: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly views: CodecTypes['pg/int4@1']['output'];
      readonly categoryId: CodecTypes['pg/int4@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly subCategoryId: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly QuizTag: {
      readonly quizId: CodecTypes['pg/text@1']['output'];
      readonly tagId: CodecTypes['pg/int4@1']['output'];
    };
    readonly SubCategory: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly categoryId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Tag: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Category: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Horoscope: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly zodiacSign:
        | 'ARIES'
        | 'TAURUS'
        | 'GEMINI'
        | 'CANCER'
        | 'LEO'
        | 'VIRGO'
        | 'LIBRA'
        | 'SCORPIO'
        | 'SAGITTARIUS'
        | 'CAPRICORN'
        | 'AQUARIUS'
        | 'PISCES';
      readonly date: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly luckyColor: CodecTypes['pg/text@1']['input'] | null;
      readonly luckyNumber: CodecTypes['pg/int4@1']['input'] | null;
      readonly mood: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly PastEvent: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly month: CodecTypes['pg/int4@1']['input'];
      readonly day: CodecTypes['pg/int4@1']['input'];
      readonly year: CodecTypes['pg/int4@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly category:
        | 'war'
        | 'discovery'
        | 'politics'
        | 'science'
        | 'art'
        | 'sports'
        | 'technology'
        | 'medicine'
        | 'exploration'
        | 'literature'
        | 'music'
        | 'economy'
        | 'religion'
        | 'disaster'
        | 'revolution'
        | 'invention';
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['input']> | null;
      readonly sourceUrls: ReadonlyArray<CodecTypes['pg/text@1']['input']> | null;
      readonly metadata: CodecTypes['pg/jsonb@1']['input'] | null;
      readonly isPublished: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly eventDate: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
    };
    readonly Question: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly quizId: CodecTypes['pg/text@1']['input'];
      readonly text: CodecTypes['pg/text@1']['input'];
      readonly options: ReadonlyArray<CodecTypes['pg/text@1']['input']> | null;
      readonly correctIndex: CodecTypes['pg/int4@1']['input'];
      readonly explanation: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Quiz: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly quizPageTitle: CodecTypes['pg/text@1']['input'];
      readonly quizPageDescription: CodecTypes['pg/text@1']['input'];
      readonly difficulty: 'easy' | 'medium' | 'hard';
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly isPublished: CodecTypes['pg/bool@1']['input'];
      readonly publishedAt: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly views: CodecTypes['pg/int4@1']['input'];
      readonly categoryId: CodecTypes['pg/int4@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly subCategoryId: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly QuizTag: {
      readonly quizId: CodecTypes['pg/text@1']['input'];
      readonly tagId: CodecTypes['pg/int4@1']['input'];
    };
    readonly SubCategory: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly categoryId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Tag: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly Category: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
    };
    readonly Horoscope: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly date: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly luckyColor: CodecTypes['pg/text@1']['output'] | null;
      readonly luckyNumber: CodecTypes['pg/int4@1']['output'] | null;
      readonly mood: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly zodiacSign:
        | 'ARIES'
        | 'TAURUS'
        | 'GEMINI'
        | 'CANCER'
        | 'LEO'
        | 'VIRGO'
        | 'LIBRA'
        | 'SCORPIO'
        | 'SAGITTARIUS'
        | 'CAPRICORN'
        | 'AQUARIUS'
        | 'PISCES';
    };
    readonly PastEvent: {
      readonly category:
        | 'war'
        | 'discovery'
        | 'politics'
        | 'science'
        | 'art'
        | 'sports'
        | 'technology'
        | 'medicine'
        | 'exploration'
        | 'literature'
        | 'music'
        | 'economy'
        | 'religion'
        | 'disaster'
        | 'revolution'
        | 'invention';
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly day: CodecTypes['pg/int4@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly eventDate: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly isPublished: CodecTypes['pg/bool@1']['output'];
      readonly metadata: CodecTypes['pg/jsonb@1']['output'] | null;
      readonly month: CodecTypes['pg/int4@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly sourceUrls: ReadonlyArray<CodecTypes['pg/text@1']['output']> | null;
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['output']> | null;
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly year: CodecTypes['pg/int4@1']['output'];
    };
    readonly Question: {
      readonly correctIndex: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly explanation: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly options: ReadonlyArray<CodecTypes['pg/text@1']['output']> | null;
      readonly quizId: CodecTypes['pg/text@1']['output'];
      readonly text: CodecTypes['pg/text@1']['output'];
    };
    readonly Quiz: {
      readonly categoryId: CodecTypes['pg/int4@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly difficulty: 'easy' | 'medium' | 'hard';
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly isPublished: CodecTypes['pg/bool@1']['output'];
      readonly publishedAt: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly quizPageDescription: CodecTypes['pg/text@1']['output'];
      readonly quizPageTitle: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
      readonly subCategoryId: CodecTypes['pg/int4@1']['output'] | null;
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly views: CodecTypes['pg/int4@1']['output'];
    };
    readonly QuizTag: {
      readonly quizId: CodecTypes['pg/text@1']['output'];
      readonly tagId: CodecTypes['pg/int4@1']['output'];
    };
    readonly SubCategory: {
      readonly categoryId: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
    };
    readonly Tag: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly Category: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
    };
    readonly Horoscope: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly date: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly luckyColor: CodecTypes['pg/text@1']['input'] | null;
      readonly luckyNumber: CodecTypes['pg/int4@1']['input'] | null;
      readonly mood: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly zodiacSign:
        | 'ARIES'
        | 'TAURUS'
        | 'GEMINI'
        | 'CANCER'
        | 'LEO'
        | 'VIRGO'
        | 'LIBRA'
        | 'SCORPIO'
        | 'SAGITTARIUS'
        | 'CAPRICORN'
        | 'AQUARIUS'
        | 'PISCES';
    };
    readonly PastEvent: {
      readonly category:
        | 'war'
        | 'discovery'
        | 'politics'
        | 'science'
        | 'art'
        | 'sports'
        | 'technology'
        | 'medicine'
        | 'exploration'
        | 'literature'
        | 'music'
        | 'economy'
        | 'religion'
        | 'disaster'
        | 'revolution'
        | 'invention';
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly day: CodecTypes['pg/int4@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly eventDate: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly isPublished: CodecTypes['pg/bool@1']['input'];
      readonly metadata: CodecTypes['pg/jsonb@1']['input'] | null;
      readonly month: CodecTypes['pg/int4@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly sourceUrls: ReadonlyArray<CodecTypes['pg/text@1']['input']> | null;
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['input']> | null;
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly year: CodecTypes['pg/int4@1']['input'];
    };
    readonly Question: {
      readonly correctIndex: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly explanation: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly options: ReadonlyArray<CodecTypes['pg/text@1']['input']> | null;
      readonly quizId: CodecTypes['pg/text@1']['input'];
      readonly text: CodecTypes['pg/text@1']['input'];
    };
    readonly Quiz: {
      readonly categoryId: CodecTypes['pg/int4@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly difficulty: 'easy' | 'medium' | 'hard';
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly isPublished: CodecTypes['pg/bool@1']['input'];
      readonly publishedAt: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly quizPageDescription: CodecTypes['pg/text@1']['input'];
      readonly quizPageTitle: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
      readonly subCategoryId: CodecTypes['pg/int4@1']['input'] | null;
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly views: CodecTypes['pg/int4@1']['input'];
    };
    readonly QuizTag: {
      readonly quizId: CodecTypes['pg/text@1']['input'];
      readonly tagId: CodecTypes['pg/int4@1']['input'];
    };
    readonly SubCategory: {
      readonly categoryId: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
    };
    readonly Tag: {
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly Category: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly slug: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['name'] },
                { readonly columns: readonly ['slug'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'Category_createdAt_idx_9575dbd7';
                  readonly prefix: 'Category_createdAt_idx';
                  readonly columns: readonly ['createdAt'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Category_slug_idx_73b7f5ce';
                  readonly prefix: 'Category_slug_idx';
                  readonly columns: readonly ['slug'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly Horoscope: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly zodiacSign: {
                  readonly nativeType: 'ZodiacSign';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: 'ZodiacSign' };
                };
                readonly date: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly luckyColor: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly luckyNumber: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly mood: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['zodiacSign', 'date'] }];
              indexes: readonly [
                {
                  readonly name: 'Horoscope_date_idx_b4ca319c';
                  readonly prefix: 'Horoscope_date_idx';
                  readonly columns: readonly ['date'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly PastEvent: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly month: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly day: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly year: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly slug: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly category: {
                  readonly nativeType: 'EventCategory';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: 'EventCategory' };
                };
                readonly tags: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly sourceUrls: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly metadata: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: true;
                };
                readonly isPublished: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly eventDate: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['month', 'day', 'year', 'slug'] }];
              indexes: readonly [
                {
                  readonly name: 'PastEvent_category_idx_f2600f8e';
                  readonly prefix: 'PastEvent_category_idx';
                  readonly columns: readonly ['category'];
                  readonly unique: false;
                },
                {
                  readonly name: 'PastEvent_eventDate_idx_8134b017';
                  readonly prefix: 'PastEvent_eventDate_idx';
                  readonly columns: readonly ['eventDate'];
                  readonly unique: false;
                },
                {
                  readonly name: 'PastEvent_month_day_category_idx_c66dc670';
                  readonly prefix: 'PastEvent_month_day_category_idx';
                  readonly columns: readonly ['month', 'day', 'category'];
                  readonly unique: false;
                },
                {
                  readonly name: 'PastEvent_month_day_idx_44d0fed4';
                  readonly prefix: 'PastEvent_month_day_idx';
                  readonly columns: readonly ['month', 'day'];
                  readonly unique: false;
                },
                {
                  readonly name: 'PastEvent_slug_idx_73b7f5ce';
                  readonly prefix: 'PastEvent_slug_idx';
                  readonly columns: readonly ['slug'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly Question: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly quizId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly text: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly options: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly correctIndex: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly explanation: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Question_quizId_idx_c721979c';
                  readonly prefix: 'Question_quizId_idx';
                  readonly columns: readonly ['quizId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Question';
                    readonly columns: readonly ['quizId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Quiz';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Quiz: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly quizPageTitle: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly quizPageDescription: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly difficulty: {
                  readonly nativeType: 'QuizDifficulty';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: 'QuizDifficulty' };
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly slug: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly isPublished: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly publishedAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly views: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly categoryId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly subCategoryId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['quizPageTitle'] },
                { readonly columns: readonly ['slug'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'Quiz_createdAt_idx_9575dbd7';
                  readonly prefix: 'Quiz_createdAt_idx';
                  readonly columns: readonly ['createdAt'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Quiz_difficulty_idx_ab7b4a75';
                  readonly prefix: 'Quiz_difficulty_idx';
                  readonly columns: readonly ['difficulty'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Quiz_isPublished_idx_d7ee5985';
                  readonly prefix: 'Quiz_isPublished_idx';
                  readonly columns: readonly ['isPublished'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Quiz_slug_idx_73b7f5ce';
                  readonly prefix: 'Quiz_slug_idx';
                  readonly columns: readonly ['slug'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Quiz_categoryId_idx_15c304f2';
                  readonly prefix: 'Quiz_categoryId_idx';
                  readonly columns: readonly ['categoryId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Quiz_subCategoryId_idx_71e8c282';
                  readonly prefix: 'Quiz_subCategoryId_idx';
                  readonly columns: readonly ['subCategoryId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Quiz';
                    readonly columns: readonly ['categoryId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Category';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Quiz';
                    readonly columns: readonly ['subCategoryId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'SubCategory';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly QuizTag: {
              columns: {
                readonly quizId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tagId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['quizId', 'tagId'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'QuizTag_quizId_idx_c721979c';
                  readonly prefix: 'QuizTag_quizId_idx';
                  readonly columns: readonly ['quizId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'QuizTag_tagId_idx_86854244';
                  readonly prefix: 'QuizTag_tagId_idx';
                  readonly columns: readonly ['tagId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'QuizTag';
                    readonly columns: readonly ['quizId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Quiz';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'QuizTag';
                    readonly columns: readonly ['tagId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Tag';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly SubCategory: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly slug: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
                readonly categoryId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['categoryId', 'name'] }];
              indexes: readonly [
                {
                  readonly name: 'SubCategory_categoryId_idx_15c304f2';
                  readonly prefix: 'SubCategory_categoryId_idx';
                  readonly columns: readonly ['categoryId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'SubCategory_slug_idx_73b7f5ce';
                  readonly prefix: 'SubCategory_slug_idx';
                  readonly columns: readonly ['slug'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'SubCategory';
                    readonly columns: readonly ['categoryId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Category';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Tag: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['name'] }];
              indexes: readonly [
                {
                  readonly name: 'Tag_name_idx_ce87e6ba';
                  readonly prefix: 'Tag_name_idx';
                  readonly columns: readonly ['name'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly EventCategory: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'war',
                'discovery',
                'politics',
                'science',
                'art',
                'sports',
                'technology',
                'medicine',
                'exploration',
                'literature',
                'music',
                'economy',
                'religion',
                'disaster',
                'revolution',
                'invention',
              ];
            };
            readonly QuizDifficulty: {
              readonly kind: 'valueSet';
              readonly values: readonly ['easy', 'medium', 'hard'];
            };
            readonly ZodiacSign: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'ARIES',
                'TAURUS',
                'GEMINI',
                'CANCER',
                'LEO',
                'VIRGO',
                'LIBRA',
                'SCORPIO',
                'SAGITTARIUS',
                'CAPRICORN',
                'AQUARIUS',
                'PISCES',
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly Category: { readonly namespace: 'public' & NamespaceId; readonly model: 'Category' };
    readonly Horoscope: { readonly namespace: 'public' & NamespaceId; readonly model: 'Horoscope' };
    readonly PastEvent: { readonly namespace: 'public' & NamespaceId; readonly model: 'PastEvent' };
    readonly SubCategory: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'SubCategory';
    };
    readonly Quiz: { readonly namespace: 'public' & NamespaceId; readonly model: 'Quiz' };
    readonly Question: { readonly namespace: 'public' & NamespaceId; readonly model: 'Question' };
    readonly Tag: { readonly namespace: 'public' & NamespaceId; readonly model: 'Tag' };
    readonly QuizTag: { readonly namespace: 'public' & NamespaceId; readonly model: 'QuizTag' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Category: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly quizzes: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Quiz' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['categoryId'];
                };
              };
              readonly subCategories: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SubCategory';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['categoryId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Category';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly slug: { readonly column: 'slug' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Horoscope: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly zodiacSign: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'ZodiacSign' };
                };
              };
              readonly date: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly luckyColor: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly luckyNumber: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly mood: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'Horoscope';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly zodiacSign: { readonly column: 'zodiacSign' };
                readonly date: { readonly column: 'date' };
                readonly description: { readonly column: 'description' };
                readonly luckyColor: { readonly column: 'luckyColor' };
                readonly luckyNumber: { readonly column: 'luckyNumber' };
                readonly mood: { readonly column: 'mood' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly PastEvent: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly month: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly day: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly year: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'EventCategory' };
                };
              };
              readonly tags: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly sourceUrls: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly metadata: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly isPublished: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly eventDate: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'PastEvent';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly month: { readonly column: 'month' };
                readonly day: { readonly column: 'day' };
                readonly year: { readonly column: 'year' };
                readonly title: { readonly column: 'title' };
                readonly slug: { readonly column: 'slug' };
                readonly description: { readonly column: 'description' };
                readonly category: { readonly column: 'category' };
                readonly tags: { readonly column: 'tags' };
                readonly sourceUrls: { readonly column: 'sourceUrls' };
                readonly metadata: { readonly column: 'metadata' };
                readonly isPublished: { readonly column: 'isPublished' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
                readonly eventDate: { readonly column: 'eventDate' };
              };
            };
          };
          readonly Question: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quizId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly text: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly options: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly correctIndex: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly explanation: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly quiz: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Quiz' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['quizId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Question';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly quizId: { readonly column: 'quizId' };
                readonly text: { readonly column: 'text' };
                readonly options: { readonly column: 'options' };
                readonly correctIndex: { readonly column: 'correctIndex' };
                readonly explanation: { readonly column: 'explanation' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Quiz: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quizPageTitle: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quizPageDescription: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly difficulty: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'QuizDifficulty' };
                };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isPublished: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly publishedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly views: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly categoryId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly subCategoryId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly category: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Category';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['categoryId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly questions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Question';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['quizId'];
                };
              };
              readonly quizTags: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'QuizTag';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['quizId'];
                };
              };
              readonly subCategory: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SubCategory';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['subCategoryId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Quiz';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly quizPageTitle: { readonly column: 'quizPageTitle' };
                readonly quizPageDescription: { readonly column: 'quizPageDescription' };
                readonly difficulty: { readonly column: 'difficulty' };
                readonly title: { readonly column: 'title' };
                readonly description: { readonly column: 'description' };
                readonly slug: { readonly column: 'slug' };
                readonly isPublished: { readonly column: 'isPublished' };
                readonly publishedAt: { readonly column: 'publishedAt' };
                readonly views: { readonly column: 'views' };
                readonly categoryId: { readonly column: 'categoryId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
                readonly subCategoryId: { readonly column: 'subCategoryId' };
              };
            };
          };
          readonly QuizTag: {
            readonly fields: {
              readonly quizId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tagId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly quiz: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Quiz' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['quizId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly tag: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Tag' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['tagId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'QuizTag';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly quizId: { readonly column: 'quizId' };
                readonly tagId: { readonly column: 'tagId' };
              };
            };
          };
          readonly SubCategory: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              readonly categoryId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly category: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Category';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['categoryId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly quizzes: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Quiz' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['subCategoryId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'SubCategory';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly slug: { readonly column: 'slug' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly categoryId: { readonly column: 'categoryId' };
              };
            };
          };
          readonly Tag: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly quizTags: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'QuizTag';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['tagId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Tag';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
